language: node_js
node_js:
- node
jobs:
  include:
  - stage: build
    script: yarn build:production && yarn build:mac && yarn build:linux && yarn build:windows
deploy:
  provider: releases
  api_key:
    secure: jDUa7D/uBcIAuKSwnyHFMENzAn0RTbg6PEqXmqkUolhNFJH3IUpqIW6FniUgqwxW766ofF91j4lT6F5Dnhhk9xwB9pdvmorkTh6u6SM/2pxN7mvKa0q3EufUHTxyAfqb+YH/LeVsDCNu3YaCr8udOrfHVXqwxybFMUX8i/+0pe8t7zg4G1aireebvVe73jeCd3ormsjg6xFUKqxezaDg8UK0+Yi2eFNgZCylI0oflS9rpyhoVgkBDlnbjIF8iBx6jsLDaKloM65mK/SuV543lnQ0NOOjR1fwItr76chfpW5OP8IL+wiCnPD8OAIZroJdiesTirsewFwbAZNkSfVgM+a6Ln2st/WVGmGbIRI+kCM/4xPEGXkrvXQlEKeoznyYEZi3l+bFZHYCbgJ99kWiwj+61YCT37UcjQq3HQMdDu8L/Tpgo2NeIFgALK7haVqx321JOSoonlZZoJtCrLBzEBVBK0Pl94VWtTZZkwRxyB87+lyKgmTSz3Yo+g2zPfRegNDWJKZbayq9kNBWtLJ2A2XCT7SOzsi3bYbJOZk3lGUYtfXqV+IbHn9TNp7743oInRLWGyRl4mrJ/mDHq6CdZ8tGZs85BRjDC5i9c6DEXemQmjArcg6ZcpeicW6SkfTWcviGx9/kByOL7T3Cu5/6Am62gzX3TO5PLrjnmFdwXK8=
  file:
  - dist/linux
  - dist/mac
  - dist/main.js
  - dist/windows.exe
  on:
    repo: Clete2/google-image-downloader
    condition: true
cache: yarn
